---
published: true
layout: post
date: 
  "Tue Apr 12 2016 14:00:00 GMT+0200 (CEST)": null
author: Start Bootstrap
"header-img": "img/post-bg-05.jpg"
---


Llevo un tiempo pensando que a mi pagina de [desarrollador web][1],, darle más vida publicando diferentes experiencias que tengo día a día en el trabajo. 
 

La primera entrada que voy a compartir con vosotros es la de como he creado este blog que es un repositorio git de github y no usa base de datos. :-)
